"""Approximate annual revenue per employer, for a size hint on the job card.

REVENUE is a curated lookup (most-recent fiscal-year total revenue, or a noted
estimate for private firms / AUM for asset managers). It is display-only —
approximate by design. Keyed by company name; lookups are tolerant of the
city/variant suffixes some scraper employer lists carry ("Accenture DAL") and
of light punctuation/casing differences between the scraped posting's company
name and the key. Companies with no meaningful/known revenue are simply absent
(the card shows nothing).
"""
import re

# City / variant tokens some scraper employer names carry as a suffix.
_SUFFIX_TOKENS = {
    "atl", "dal", "dc", "hou", "mia", "gh", "na", "campus", "inc",
}

# {company name: revenue string}
REVENUE: dict[str, str] = {
    # ── Top-10-city $1B+ wave (2026-07-19) ──
    'Ares Management': '$5.2B',
    'Axalta': '$5.3B',
    'Axon': '$2.1B',
    'Banner Health': '~$14B',
    'Baxter': '$11B',
    'CDW': '$21B',
    "Campbell's": '$10B',
    'Capital Group': '~$9B (est.)',
    'Carpenter Technology': '$2.9B',
    'Cboe Global Markets': '$4.1B',
    'Cencora': '$321B',
    'Chemours': '$5.8B',
    'Citigroup': '$81B',
    'Clear Channel Outdoor': '$2.2B',
    'Conagra Brands': '$12B',
    'Cubic': '~$1.5B (est.)',
    'DIRECTV': '~$28B (est.)',
    'Dexcom': '$4B',
    'DuPont': '$12B',
    'Dun & Bradstreet': '$2.4B',
    'FMC Corporation': '$4.2B',
    'Fanatics': '~$8B (est.)',
    'Five Below': '$4.8B',
    'Frost Bank': '$2.1B',
    'GE HealthCare': '$20B',
    'Illumina': '$4.3B',
    'Ingram Micro': '$48B',
    'Jefferson Health': '~$12B',
    'Microchip Technology': '$4.4B',
    'Mondelez': '$36B',
    'Morningstar': '$2.3B',
    'Neurocrine Biosciences': '$2.4B',
    'Northern Trust': '$8.3B',
    'Oaktree Capital': '~$2.5B (est.)',
    'PGA Tour': '~$1.9B',
    'Pacific Life': '~$10B',
    'Penn Mutual': '$7.1B',
    'RYAM': '$1.6B',
    'Rackspace': '$2.7B',
    'Realty Income': '$5.3B',
    'Republic Services': '$16B',
    'ResMed': '$5.1B',
    'Sharp HealthCare': '~$4.9B',
    'Skechers': '$9B',
    'Sony Electronics': '$88B',
    'Sony Pictures': '$10B',
    'Taylor Morrison': '$8.2B',
    'Topgolf Callaway': '$4.2B',
    'TransUnion': '$4.2B',
    'U-Haul': '$5.8B',
    'UPenn': '~$16B',
    'US Foods': '$38B',
    'USAA': '$48B',
    'Universal Music Group': '$13B',
    'Western Alliance Bank': '$3.2B',
    'Whataburger': '~$3.5B (est.)',
    'Wintrust Financial': '$2.4B',
    'Zebra Technologies': '$5B',
    'iHeartMedia': '$3.9B',
    # ── (pre-2026-07-19 entries) ──
    '10x Genomics': '$610M',
    '2U': '$800M',
    '3M': '$24B',
    'AIG': '$47B',
    'AQR Capital': '~$130B AUM',
    'AT&T': '$122B',
    'AWS': '$108B',
    'Abbott': '$42B',
    'Academy Sports': '$6B',
    'Accenture': '$65B',
    'Adobe': '$21B',
    'Adyen': '~$2B',
    'Affirm': '$2.3B',
    'Airbnb': '$11B',
    'Alloy': '~$100M (est.)',
    'Allstate': '$64B',
    'Ally Financial': '$8B',
    'American Express': '$66B',
    'Amgen': '$33B',
    'Amplitude': '$300M',
    'Analog Devices': '$9.4B',
    'Anthropic': '~$1B (est.)',
    'Apollo': '~$26B',
    'Applied Materials': '$27B',
    'Aptiv': '$20B',
    'Asana': '$700M',
    'Assurant': '$12B',
    'Atrium Health': '~$8B',
    'Attentive': '~$500M (est.)',
    'Avnet': '$24B',
    'BAE Systems': '$33B',
    'BNY': '$18B',
    'BNY Mellon': '$18B',
    'Baker Hughes': '$28B',
    'Bank of America': '$100B',
    'Barclays': '$33B',
    'Becton Dickinson': '$20B',
    'Benefitfocus': '~$260M',
    'Bill.com': '$1.3B',
    'Bird': '~$100M',
    'BlackRock': '$20B',
    'Blackstone': '$13B',
    'Block': '$24B',
    'Boeing': '$67B',
    'Boingo Wireless': '~$270M',
    'Booz Allen': '$11B',
    'BorgWarner': '$14B',
    'Box': '$1B',
    'Braze': '$550M',
    'Brex': '~$300M (est.)',
    'Bridgewater': '~$100B AUM',
    'Bristol-Myers': '$48B',
    'Burlington': '$10B',
    'ByteDance': '~$120B (est.)',
    'C3.ai': '$310M',
    'CBRE': '$35B',
    'CME Group': '$6B',
    'CNA Financial': '$13B',
    'CVS Health': '$373B',
    'Calendly': '~$200M (est.)',
    'Calm': '~$300M (est.)',
    'Capital One': '$39B',
    'Cardinal Health': '$227B',
    'Cardlytics': '$300M',
    'Carta': '~$400M (est.)',
    "Carter's": '$2.8B',
    'Carvana': '$13B',
    'Celonis': '~$400M (est.)',
    'Centene': '$163B',
    'Checkr': '~$400M (est.)',
    'Chevron': '$200B',
    'Chewy': '$11B',
    'Chick-fil-A': '~$21B',
    'Chime': '~$1.7B (est.)',
    'Chipotle': '$11B',
    'Choice Hotels': '$1.7B',
    'Chord Energy': '$4B',
    'Cigna': '$247B',
    'Cisco': '$54B',
    'Citadel': '~$65B AUM',
    'Cloudflare': '$1.7B',
    'Coca-Cola': '$47B',
    'Cockroach Labs': '~$150M (est.)',
    'Coinbase': '$6.6B',
    'Comcast': '$124B',
    'Comfort Systems USA': '$7B',
    'Compass': '$5.6B',
    'ConocoPhillips': '$57B',
    'Corebridge Financial': '~$17B',
    'Cornerstone OnDemand': '~$900M (est.)',
    'Corpay': '$4B',
    'Coupang': '$30B',
    'Coursera': '$700M',
    'Cox Enterprises': '~$23B',
    'CrowdStrike': '$3.9B',
    'Crown Holdings': '$12B',
    'Crunchyroll': '~$1B (est.)',
    'D.E. Shaw': '~$60B AUM',
    'DNOW': '$2.4B',
    'Databricks': '~$2.4B (est.)',
    'Datadog': '$2.7B',
    'Dell': '$96B',
    'Deloitte': '$67B',
    'Delta Air Lines': '$61B',
    'Deutsche Bank': '$33B',
    'Devon Energy': '$15B',
    'Diageo': '$20B',
    'Discover': '$18B',
    'Dollar Shave Club': '~$200M (est.)',
    'DoorDash': '$10.7B',
    'DoubleVerify': '$650M',
    'Dr Squatch': '~$400M (est.)',
    'Dropbox': '$2.5B',
    'Duke Energy': '$30B',
    'Duolingo': '$750M',
    'EOG Resources': '$24B',
    'Ecolab': '$16B',
    'Edwards Lifesciences': '$5.4B',
    'Elastic': '$1.4B',
    'Elevance Health': '$175B',
    'Equifax': '$5.7B',
    'Equinix': '$8.7B',
    'Erickson Senior Living': '~$2B (est.)',
    'Everest': '$18B',
    'Expedia': '$13.7B',
    'ExxonMobil': '$340B',
    'FIS': '$10B',
    'FMC': '$4.2B',
    'FactSet': '$2.2B',
    'Faire': '~$700M (est.)',
    'FanDuel': '~$6B',
    'Fannie Mae': '$30B',
    'Fidelity': '~$28B',
    'Figma': '~$1B (est.)',
    'Fiserv': '$20B',
    'Fivetran': '~$300M (est.)',
    'Flex': '$26B',
    'Flexport': '~$2B (est.)',
    'Fox Corp': '$14B',
    'Freddie Mac': '$22B',
    'GE Vernova': '$35B',
    'GOAT Group': '~$600M (est.)',
    'Gartner': '$6.3B',
    'General Dynamics': '$48B',
    'Genuine Parts': '$23B',
    'Gilead': '$29B',
    'Ginkgo Bioworks': '$250M',
    'GitLab': '$760M',
    'Global Payments': '$10B',
    'Glossier': '~$300M (est.)',
    'Goldman Sachs': '$53B',
    'Goodyear': '$19B',
    'Grafana Labs': '~$400M (est.)',
    'Greenhouse Software': '~$200M (est.)',
    'Guardian Life': '$13B',
    'Guild': '~$400M (est.)',
    'GumGum': '~$150M (est.)',
    'Gusto': '~$500M (est.)',
    'HD Supply': '~$7B',
    'HP Enterprise': '$30B',
    'HP Inc': '$53B',
    'HSBC': '$66B',
    'Halliburton': '$23B',
    'Highmark': '$27B',
    'Hilton': '$11B',
    'Home Depot': '$160B',
    'Honeywell': '$38B',
    'HubSpot': '$2.6B',
    'Humana': '$117B',
    'IBM': '$62B',
    'ICE': '$9.3B',
    'Illinois Tool Works': '$16B',
    'Ingevity': '$1.4B',
    'Inspire Brands': '~$30B',
    'Instacart': '$3.4B',
    'Intel': '$53B',
    'Invesco': '$6B',
    'Iterable': '~$150M (est.)',
    'JFrog': '$430M',
    'JLL': '$23B',
    'JPMorgan': '$178B',
    'Jabil': '$28B',
    'Jacobs': '$16B',
    'Jane Street': '~$20B',
    'Jefferies': '$7B',
    'Johnson & Johnson': '$88B',
    'Johnson Controls': '$23B',
    'KBR': '$7.7B',
    'KION Group': '~$12B',
    'KKR': '$21B',
    'KeyBank': '$7B',
    'Kimberly-Clark': '$20B',
    'Klaviyo': '$940M',
    'Komodo Health': '~$150M (est.)',
    'LPL Financial': '$12B',
    'Labcorp': '$13B',
    'Las Vegas Sands': '$11.3B',
    'Lattice': '~$100M (est.)',
    'Leidos': '$16.7B',
    'Lennar': '$35B',
    'LinkedIn': '~$16B',
    'Liquid Death': '~$400M (est.)',
    'Lockheed Martin': '$71B',
    'Lucid Motors': '$800M',
    'Lyft': '$5.8B',
    'M&T Bank': '$9B',
    'MUSC': '~$4.5B',
    'Man Group': '~$180B AUM',
    'Manhattan Assoc': '$1B',
    'Marathon Petroleum': '$138B',
    'Marqeta': '$680M',
    'Marriott': '$25B',
    'Mars': '~$50B',
    'Marsh McLennan': '$24B',
    'Marvell': '$5.8B',
    'MassMutual': '~$35B',
    'Mastercard': '$28B',
    'McKesson': '$309B',
    'Medifast': '$1B',
    'Medtronic': '$32B',
    'Merck': '$64B',
    'Michelin': '~$30B',
    'Micron': '$25B',
    'Microsoft': '$245B',
    'Millennium Management': '~$70B AUM',
    'Millennium Mgmt': '~$70B AUM',
    'Millennium Mgt': '~$70B AUM',
    'Mixpanel': '~$100M (est.)',
    'MongoDB': '$2B',
    'Morgan Stanley': '$61B',
    'Motorola Solutions': '$11B',
    'Movement Mortgage': '~$1B (est.)',
    'NCR Atleos': '$4.3B',
    'NCR Voyix': '$3.6B',
    'NRG Energy': '$28B',
    'NTT Data': '$30B',
    'NXP': '$13B',
    'NY Times': '$2.6B',
    'Nasdaq': '$7B',
    'Natera': '$1.7B',
    'Nationwide': '~$50B',
    'Netflix': '$39B',
    'New Relic': '~$1B',
    'New York Times': '$2.6B',
    'Nomura': '$18B',
    'Norfolk Southern': '$12B',
    'Northrop Grumman': '$41B',
    'Northwestern Mut': '~$35B',
    'Northwestern Mutual': '~$35B',
    'Norwegian Cruise': '$9.5B',
    'Nubank': '$11B',
    'Occidental': '$27B',
    'Okta': '$2.6B',
    'Old Dominion': '$5.8B',
    'OpenX': '~$400M (est.)',
    'Oracle': '$57B',
    'Oura': '~$500M (est.)',
    'PNC Financial': '$21B',
    'PPG': '$16B',
    'PVH Corp': '$9B',
    'Palantir': '$2.9B',
    'PayPal': '$32B',
    'Peloton': '$2.7B',
    'Penn Medicine': '~$10B',
    'PepsiCo': '$92B',
    'Pfizer': '$64B',
    'Phillips 66': '$143B',
    'Pinterest': '$3.6B',
    'Plains All American': '$50B',
    'Planet Labs': '$240M',
    'Point72': '~$35B AUM',
    'Porsche Cars': '~$44B',
    'Postman': '~$200M (est.)',
    'Prisma Health': '~$5B',
    'Prudential': '$60B',
    'PwC': '$55B',
    'Qualcomm': '$39B',
    'Qualys': '$600M',
    'Raymond James': '$12B',
    'Raytheon': '$80B',
    'Recursion': '$80M',
    'Red Ventures': '~$4B (est.)',
    'Reddit': '$1.3B',
    'Regeneron': '$14B',
    'Regions Financial': '$7B',
    'RingCentral': '$2.4B',
    'Riot Games': '~$4B (est.)',
    'Rite Aid': '~$24B',
    'Ro': '~$500M (est.)',
    'Robinhood': '$2.9B',
    'Roblox': '$3.6B',
    'Roper St. Francis': '~$2B',
    'Roper Tech': '$7B',
    'Ryder System': '$12.6B',
    'S&P Global': '$14B',
    'SAIC': '$7.4B',
    'SAP': '$37B',
    'Salesforce': '$38B',
    'Samsara': '$1.2B',
    'Schlumberger': '$36B',
    'Scopely': '~$2B (est.)',
    'SeatGeek': '~$400M (est.)',
    'SecureWorks': '$450M',
    'Service Corp Intl': '$4B',
    'ServiceNow': '$11B',
    'Shell': '$284B',
    'Sigma Computing': '~$100M (est.)',
    'Smartsheet': '$1B',
    'Snap': '$5.4B',
    'SoFi': '$2.7B',
    'Sonoco': '$5.3B',
    'SouthState Bank': '$2B',
    'Southern Company': '$26B',
    'Southwest Airlines': '$27B',
    'SpaceX': '~$13B (est.)',
    'Spotify': '$17B',
    'Squarespace': '$1.2B',
    'Stanley Black & Decker': '$15.4B',
    'State Street': '$13B',
    'Stewart Title': '$2.5B',
    'Stripe': '~$5B (est.)',
    'Stryker': '$22B',
    'Sumo Logic': '~$300M',
    'Sweetgreen': '$680M',
    'Synchrony': '$15B',
    'Sysco': '$79B',
    'System1': '$400M',
    'T-Mobile': '$81B',
    'T. Rowe Price': '$7B',
    'TIAA': '~$40B',
    'Tala': '~$200M (est.)',
    'Tapestry': '$6.7B',
    'Targa Resources': '$16B',
    'Target': '$107B',
    'Tebra': '~$300M (est.)',
    'Tenet Healthcare': '$20B',
    'Texas Instruments': '$16B',
    'The Hartford': '$26B',
    'The Honest Company': '$380M',
    'The Trade Desk': '$2.4B',
    'Thermo Fisher': '$43B',
    'Thomson Reuters': '$7B',
    'Thrive Market': '~$700M (est.)',
    'Toast': '$4.9B',
    'Toyota': '$300B',
    'Trane Technologies': '$19B',
    'Travelers': '$46B',
    'Trimble': '$3.7B',
    'Truist Financial': '$20B',
    'Twilio': '$4.5B',
    'UBS': '$40B',
    'UPS': '$91B',
    'Uber': '$44B',
    'Udemy': '$780M',
    'Unisys': '$2B',
    'Unity Technologies': '$1.8B',
    'Unum': '$12B',
    'Unum / Colonial Life': '$12B',
    'Upstart': '$650M',
    'VF Corporation': '$10B',
    'Vanguard': '~$8B',
    'Veeva': '$2.7B',
    'Veeva Systems': '$2.7B',
    'Vercel': '~$200M (est.)',
    'Veritiv': '~$7B',
    'Verizon': '$134B',
    'Via': '~$400M (est.)',
    'Virtu Financial': '$2.5B',
    'Visa': '$36B',
    'Walmart': '$681B',
    'Walt Disney': '$91B',
    'Warner Bros': '$40B',
    'Waste Management': '$22B',
    'Webflow': '~$200M (est.)',
    'Wells Fargo': '$82B',
    'Westlake': '$12B',
    'Williams': '$10.5B',
    'Workday': '$8.4B',
    'Workday Inc': '$8.4B',
    'World Fuel Svc': '$47B',
    'Xcel Energy': '$14B',
    'ZipRecruiter': '$475M',
    'ZoomInfo': '$1.2B',

    # ── Backfill of the 30 configured employers that had no row (2026-07-21) ──
    # Every one was scraped and shown with a blank size hint. Researched
    # against FY2025 filings where public; private firms carry the best
    # credible estimate and the '(est.)' marker. Keys are the CANONICAL name —
    # _canonical() strips the config's "NA"/"Campus" suffixes first, so
    # "Toyota NA" resolves to 'Toyota' and "M&T Bank Campus" to 'M&T Bank'.
    'Astranis': '~$11M (est.)',
    'Aurora': '$3M',
    'Boulevard': '~$71M (est.)',
    # NOTE: the greenhouse token "branch" is Branch Messenger, NOT the
    # Branch Metrics (branch.io) this entry was presumably meant to track.
    # All three Branches are far under $1B, so the size hint is right either
    # way — but the employer config is probably pointing at the wrong company.
    'Branch': '~$130M (est.)',
    'Cheniere Energy': '$20B',
    'ClassPass': '~$120M (est.)',
    'ClickHouse': '~$250M (est.)',
    'Culture Amp': '~$230M (est.)',
    'Faraday Future': '$0.5M',
    # Roche never breaks Flatiron out; public estimates span $375M–$1.2B, so
    # this is the one genuinely uncertain call in the backfill.
    'Flatiron Health': '~$530M (est.)',
    'Gemini': '$180M',
    'Group 1 Automotive': '$22.6B',
    'IMC Trading': '$3.1B',
    'Imply': '~$63M (est.)',
    # Nothing disclosed; aggregators say $0.5–1.2B, insiders imply several
    # billion. Treated as $1B+ but it's the weakest call on this list.
    'Jump Trading': '~$2B (est.)',
    'Kinder Morgan': '$17B',
    'Kirby': '$3.4B',
    'M&T Bank': '$9.7B',
    'Mythical Games': '~$60M (est.)',
    'NOV': '$8.7B',
    'Nuro': '~$190M (est.)',
    'Oceaneering': '$2.8B',
    'Patterson-UTI': '$4.8B',
    'Quanta Services': '$28B',
    'Relativity Space': '~$270M (est.)',
    'Temporal': '~$60M (est.)',
    # TMC's North America geographic segment — Toyota Motor North America
    # files no standalone financials.
    'Toyota': '$140B',
    'Waymo': '~$280M (est.)',
    'Meta': '$201B',
    # Wayve is deliberately absent: its latest Companies House accounts
    # describe it as pre-revenue R&D, and the module's convention is that
    # companies with no meaningful revenue carry no row at all.
}


def _norm(name: str) -> str:
    """Lowercase, drop punctuation, collapse whitespace."""
    return re.sub(r"[^a-z0-9]+", " ", (name or "").lower()).strip()


def _canonical(name: str) -> str:
    """Strip trailing city/variant tokens: 'Accenture DAL' -> 'Accenture'."""
    parts = (name or "").split()
    while len(parts) > 1 and parts[-1].lower().strip(".,") in _SUFFIX_TOKENS:
        parts = parts[:-1]
    return " ".join(parts).strip()


def _candidates(name: str):
    """Every progressively-stripped form of a name, longest first.

    Stripping straight to the shortest form loses matches when a real part of
    the name is also a suffix token: "HP Inc HOU" drops HOU *and* Inc down to
    "HP", which has no row, so HP's $53B never rendered. Trying each step means
    the 'HP Inc' key is found on the way past.
    """
    seen = []
    parts = (name or "").split()
    while parts:
        candidate = " ".join(parts).strip()
        if candidate and candidate not in seen:
            seen.append(candidate)
        if len(parts) == 1 or parts[-1].lower().strip(".,") not in _SUFFIX_TOKENS:
            break
        parts = parts[:-1]
    return seen


# Normalized index so a scraped "BNY" resolves to the "BNY Mellon" key, etc.
_NORM_INDEX = {_norm(k): v for k, v in REVENUE.items()}


def revenue_for(company: str):
    """Return the revenue string for a company, or None if unknown."""
    if not company:
        return None
    candidates = _candidates(company)
    for key in candidates:
        if key in REVENUE:
            return REVENUE[key]
    for key in candidates:
        hit = _NORM_INDEX.get(_norm(key))
        if hit:
            return hit
    return None
